// <auto-generated />
using System;
using AttendanceManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AttendanceManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.Assistant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporter_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_assistant");

                    b.HasIndex("TransporterId")
                        .HasDatabaseName("ix_assistant_transporter");

                    b.HasIndex("UserAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_assistant_user_account");

                    b.ToTable("assistant", (string)null);
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttendanceSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_session_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Justification")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("justification");

                    b.Property<Guid?>("JustifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("justified_by");

                    b.Property<Guid?>("PickedUpByGuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("picked_up_by_guardian_id");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporter_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_attendance_record");

                    b.HasIndex("JustifiedBy")
                        .HasDatabaseName("ix_attendance_record_justified_by");

                    b.HasIndex("PickedUpByGuardianId")
                        .HasDatabaseName("ix_attendance_record_picked_up_by_guardian_id");

                    b.HasIndex("RecordedBy")
                        .HasDatabaseName("ix_attendance_record_recorded_by");

                    b.HasIndex("AttendanceSessionId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_record_session_student");

                    b.HasIndex("StudentId", "RecordedAtUtc")
                        .HasDatabaseName("ix_attendance_record_student_date");

                    b.HasIndex("TransporterId", "RecordedAtUtc")
                        .HasDatabaseName("ix_attendance_record_picked_up")
                        .HasFilter("status = 'PickedUpByGuardian'");

                    b.ToTable("attendance_record", null, t =>
                        {
                            t.HasCheckConstraint("ck_attendance_record_status", "status IN ('Present','Absent','Late','PickedUpByGuardian','Justified')");
                        });
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.AttendanceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssistantId")
                        .HasColumnType("uuid")
                        .HasColumnName("assistant_id");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_utc");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("session_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransportGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_group_id");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporter_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_attendance_session");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_attendance_session_created_by");

                    b.HasIndex("TransporterId", "SessionDate")
                        .HasDatabaseName("ix_attendance_session_transporter_date");

                    b.HasIndex("TransportGroupId", "SessionDate", "SessionType")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_session_group_date_type");

                    b.ToTable("attendance_session", null, t =>
                        {
                            t.HasCheckConstraint("ck_attendance_session_status", "status IN ('Open','Closed','Canceled')");

                            t.HasCheckConstraint("ck_attendance_session_type", "session_type IN ('ToSchool','FromSchool')");
                        });
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TransportGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_group_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_enrollment");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_enrollment_student");

                    b.HasIndex("TransportGroupId")
                        .HasDatabaseName("ix_enrollment_transport_group");

                    b.HasIndex("StudentId", "TransportGroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_enrollment_active")
                        .HasFilter("active");

                    b.ToTable("enrollment", (string)null);
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.EventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporter_id");

                    b.HasKey("Id")
                        .HasName("pk_event_log");

                    b.HasIndex("TransporterId", "OccurredAtUtc")
                        .HasDatabaseName("ix_event_log_transporter_date");

                    b.HasIndex("AggregateType", "AggregateId", "OccurredAtUtc")
                        .HasDatabaseName("ix_event_log_aggregate");

                    b.ToTable("event_log", (string)null);
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.Guardian", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("contact_email");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Mobile")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporter_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id")
                        .HasName("pk_guardian");

                    b.HasIndex("TransporterId")
                        .HasDatabaseName("ix_guardian_transporter");

                    b.HasIndex("UserAccountId")
                        .HasDatabaseName("ix_guardian_user_account");

                    b.ToTable("guardian", (string)null);
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.GuardianStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool>("CanPickup")
                        .HasColumnType("boolean")
                        .HasColumnName("can_pickup");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<Guid>("GuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("guardian_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("relationship");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_guardian_student");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_guardian_student_primary")
                        .HasFilter("is_primary AND active");

                    b.HasIndex("GuardianId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_guardian_student_pair");

                    b.ToTable("guardian_student", (string)null);
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporter_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_school");

                    b.HasIndex("TransporterId")
                        .HasDatabaseName("ix_school_transporter");

                    b.HasIndex("TransporterId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_school_transporter_name");

                    b.ToTable("school", (string)null);
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Grade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grade");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporter_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_student");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_student_school");

                    b.HasIndex("TransporterId")
                        .HasDatabaseName("ix_student_transporter");

                    b.HasIndex("UserAccountId")
                        .HasDatabaseName("ix_student_user_account_id");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.TransportGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssistantId")
                        .HasColumnType("uuid")
                        .HasColumnName("assistant_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Shift")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("shift");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporter_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_transport_group");

                    b.HasIndex("AssistantId")
                        .HasDatabaseName("ix_transport_group_assistant_id");

                    b.HasIndex("TransporterId")
                        .HasDatabaseName("ix_transport_group_transporter");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_transport_group_vehicle_id");

                    b.ToTable("transport_group", (string)null);
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.Transporter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("business_phone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("document_number");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("document_type");

                    b.Property<string>("LicenseCategory")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("license_category");

                    b.Property<DateOnly?>("LicenseExpiry")
                        .HasColumnType("date")
                        .HasColumnName("license_expiry");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_transporter");

                    b.HasIndex("DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_transporter_document");

                    b.HasIndex("UserAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_transporter_user_account");

                    b.ToTable("transporter", (string)null);
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmed_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("PrimaryRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("primary_role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_user_account");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_account_email");

                    b.ToTable("user_account", (string)null);
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Model")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("model");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("plate");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporter_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_vehicle");

                    b.HasIndex("TransporterId")
                        .HasDatabaseName("ix_vehicle_transporter");

                    b.HasIndex("TransporterId", "Plate")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_transporter_plate");

                    b.ToTable("vehicle", (string)null);
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.Assistant", b =>
                {
                    b.HasOne("AttendanceManagement.Domain.Entities.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assistant_transporters_transporter_id");

                    b.HasOne("AttendanceManagement.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assistant_user_accounts_user_account_id");
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("AttendanceManagement.Domain.Entities.AttendanceSession", null)
                        .WithMany()
                        .HasForeignKey("AttendanceSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_record_attendance_sessions_attendance_session_id");

                    b.HasOne("AttendanceManagement.Domain.Entities.Guardian", null)
                        .WithMany()
                        .HasForeignKey("JustifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attendance_record_guardians_justified_by");

                    b.HasOne("AttendanceManagement.Domain.Entities.Guardian", null)
                        .WithMany()
                        .HasForeignKey("PickedUpByGuardianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attendance_record_guardians_picked_up_by_guardian_id");

                    b.HasOne("AttendanceManagement.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("RecordedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_record_user_accounts_recorded_by");

                    b.HasOne("AttendanceManagement.Domain.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_record_students_student_id");

                    b.HasOne("AttendanceManagement.Domain.Entities.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_record_transporters_transporter_id");
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.AttendanceSession", b =>
                {
                    b.HasOne("AttendanceManagement.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_session_user_accounts_created_by");

                    b.HasOne("AttendanceManagement.Domain.Entities.TransportGroup", null)
                        .WithMany()
                        .HasForeignKey("TransportGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_session_transport_groups_transport_group_id");

                    b.HasOne("AttendanceManagement.Domain.Entities.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_session_transporters_transporter_id");
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("AttendanceManagement.Domain.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_enrollment_students_student_id");

                    b.HasOne("AttendanceManagement.Domain.Entities.TransportGroup", null)
                        .WithMany()
                        .HasForeignKey("TransportGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_enrollment_transport_groups_transport_group_id");
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.EventLog", b =>
                {
                    b.HasOne("AttendanceManagement.Domain.Entities.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_log_transporters_transporter_id");
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.Guardian", b =>
                {
                    b.HasOne("AttendanceManagement.Domain.Entities.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guardian_transporters_transporter_id");

                    b.HasOne("AttendanceManagement.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guardian_user_accounts_user_account_id");

                    b.OwnsOne("AttendanceManagement.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("GuardianId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_complement");

                            b1.Property<string>("District")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_district");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("address_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("address_longitude");

                            b1.Property<string>("Number")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_number");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("State")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_street");

                            b1.HasKey("GuardianId");

                            b1.ToTable("guardian");

                            b1.WithOwner()
                                .HasForeignKey("GuardianId")
                                .HasConstraintName("fk_guardian_guardian_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.GuardianStudent", b =>
                {
                    b.HasOne("AttendanceManagement.Domain.Entities.Guardian", null)
                        .WithMany()
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guardian_student_guardian_guardian_id");

                    b.HasOne("AttendanceManagement.Domain.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guardian_student_students_student_id");
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.School", b =>
                {
                    b.HasOne("AttendanceManagement.Domain.Entities.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_school_transporters_transporter_id");

                    b.OwnsOne("AttendanceManagement.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("SchoolId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_complement");

                            b1.Property<string>("District")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_district");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("address_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("address_longitude");

                            b1.Property<string>("Number")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_number");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("State")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_street");

                            b1.HasKey("SchoolId");

                            b1.ToTable("school");

                            b1.WithOwner()
                                .HasForeignKey("SchoolId")
                                .HasConstraintName("fk_school_school_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.Student", b =>
                {
                    b.HasOne("AttendanceManagement.Domain.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_student_school_school_id");

                    b.HasOne("AttendanceManagement.Domain.Entities.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_transporters_transporter_id");

                    b.HasOne("AttendanceManagement.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_student_user_accounts_user_account_id");
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.TransportGroup", b =>
                {
                    b.HasOne("AttendanceManagement.Domain.Entities.Assistant", null)
                        .WithMany()
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transport_group_assistant_assistant_id");

                    b.HasOne("AttendanceManagement.Domain.Entities.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transport_group_transporters_transporter_id");

                    b.HasOne("AttendanceManagement.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transport_group_vehicles_vehicle_id");
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.Transporter", b =>
                {
                    b.HasOne("AttendanceManagement.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transporter_user_accounts_user_account_id");
                });

            modelBuilder.Entity("AttendanceManagement.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("AttendanceManagement.Domain.Entities.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_transporter_transporter_id");
                });
#pragma warning restore 612, 618
        }
    }
}
